config/routes.rb
Rails.application.routes.draw do
  root 'charges#index'
  get 'charges/create'
  get 'charges/new'
  get 'charges/add_wishes'

  resources :charges

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
  	@amount = 500

		customer = Stripe::Customer.create(
			:email => 'example@stripe.com',
			:card => params[:stripeToken]
		)

		charge = Stripe::Charge.create(
			:customer => customer.id,
			:amount => @amount,
			:description => 'Rails Stripe customer',
			:currency => 'usd'
		)

		rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to charges_path
  end

  def new
  end

  def index
  end
  def add_wishes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/add_wishes.html.erb
 <div class="row">
 	  <div class="col-md-6 col-md-offset-3">
 	  	<form>
		 	 <h4>Monthly Contribution</h4>
		 	<div class="form-group">
		    <input type="text" class= "form-control input-lg", placeholder = "$">
		  </div><br/>
		  <h4>Enter Your Wishes (Amazon URLs)</h4>
		 <div class="form-group">
		    <input type="text" class= "form-control input-lg", placeholder = "Wish 1">
		  </div>
		  <div class="form-group">
		    <input type="text" class= "form-control input-lg", placeholder = "Wish 2">
		  </div>
		   <div class="form-group">
		    <input type="text" class= "form-control input-lg", placeholder = "Wish 3">
		  </div>
		 <p align="center"><%= link_to "Sign Up", charges_new_path, class: "btn btn-lg btn-success" %></p>
		</form>
	</div>
</div>

app/views/charges/create.html.erb
<h1>Now Sit and Wait</h1>
<p>We'll surprise you in the near future with an item from your list!</p>

app/views/charges/index.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="bs-example" data-example-id="carousel-with-captions">
		    <div id="carousel-example-captions" class="carousel slide" data-ride="carousel">
		      
		      <div class="carousel-inner" role="listbox">
		        <div class="item active">
		          <%= image_tag "sweater.jpg", alt: "sweater" %>
		          <div class="carousel-caption">
		            <h1>Cashmere sweaters, a table saw, a moped...</h1>
				    <h2>Things you really want, but wouldn't normally buy yourself</h2>
		          </div>
		        </div>
		        <div class="item">
		          <%= image_tag "moped.jpg", alt: "moped" %>

		          <div class="carousel-caption">
		             <h1>Choose 3 luxury items that really melt your butter and let us help you set aside the bacon.</h1>  
			   		<h2>Before you know it we'll surprise you one of the items you lust for.</h2>
		          </div>
		        </div>
		      </div>
		      <a class="left carousel-control" href="#carousel-example-captions" role="button" data-slide="prev">
		        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		        <span class="sr-only">Previous</span>
		      </a>
		      <a class="right carousel-control" href="#carousel-example-captions" role="button" data-slide="next">
		        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		        <span class="sr-only">Next</span>
		      </a>
		    </div>
		</div>
	</div>
</div>
<br/>
<p align="center"><%= link_to "Create Your List", charges_add_wishes_path, class: "btn btn-lg btn-success" %></p>

app/views/charges/new.html.erb
<h1>Your Wish List</h1><br/>

<div class="row">
  <div class="col-md-4">
  	<div class="well">
	  	<h3>The Clapper Sound Activated On/Off Switch</h3>
	  	<%= image_tag "clapper.jpg", class: "img-responsive" %><br/>
	  	<a href="http://www.amazon.com/Clapper-Sound-Activated-Switch-Each/dp/B0000CGKLR/ref=sr_1_1?ie=UTF8&qid=1426023567&sr=8-1&keywords=the+clapper" class="btn btn-default" class="btn btn-default">View on Amazon</a>
	 </div>
  </div>
  <div class="col-md-4">
  	<div class="well">
  		<h3>SmartWool Margarita Womens Socks</h3>
  	  <%= image_tag "socks.jpeg", class: "img-responsive" %>
  	  <br/><a href="http://www.amazon.com/SmartWool-Margarita-Sock-Womens-Heather/dp/B006RFQVUU/ref=sr_1_2?ie=UTF8&qid=1426023853&sr=8-2&keywords=smartwool+socks" class="btn btn-default">View on Amazon</a>
  	 </div>
  </div>
  <div class="col-md-4">
  	<div class="well">
  	<h3>DEWALT DW745 10-Inch Compact Job-Site Table Saw</h3>
  	<%= image_tag "saw.jpg", class: "img-responsive" %><br/>
  	  <a href="http://www.amazon.com/DEWALT-DW745-10-Inch-Job-Site-Capacity/dp/B000HXT2N6/ref=sr_1_1?s=power-hand-tools&ie=UTF8&qid=1426023940&sr=1-1&keywords=table+saw" class="btn btn-default">View on Amazon</a>
  	 </div>
  </div>
</div>

<div>
<%= form_tag charges_path do %>
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">

	<div id="contribution">
		<h3>Monthly Contribution: $20.00<br/><br/>
		<script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%=Rails.configuration.stripe[:publishable_key] %>" data-description="A month's subscription" data-amount="2000"></script></h3>
	  </div>
  <% end %>
  </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StripeExample</title>

<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
	<div align="center">
		<header><i class="glyphicon glyphicon-gift"></i> Treat Yo'self
		</header>
<div class="container">
	<%= yield %>
</div>

</body>
</html>